/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResellersOgRouteImport } from './routes/resellers-og'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as AdminOgRouteImport } from './routes/admin-og'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDownloadExtensionRouteImport } from './routes/api.public.download-extension'

const ResellersOgRoute = ResellersOgRouteImport.update({
  id: '/resellers-og',
  path: '/resellers-og',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOgRoute = AdminOgRouteImport.update({
  id: '/admin-og',
  path: '/admin-og',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadExtensionRoute =
  ApiPublicDownloadExtensionRouteImport.update({
    id: '/api/public/download-extension',
    path: '/api/public/download-extension',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-og': typeof AdminOgRoute
  '/extension': typeof ExtensionRoute
  '/resellers-og': typeof ResellersOgRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-og': typeof AdminOgRoute
  '/extension': typeof ExtensionRoute
  '/resellers-og': typeof ResellersOgRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-og': typeof AdminOgRoute
  '/extension': typeof ExtensionRoute
  '/resellers-og': typeof ResellersOgRoute
  '/api/public/download-extension': typeof ApiPublicDownloadExtensionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-og'
    | '/extension'
    | '/resellers-og'
    | '/api/public/download-extension'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-og'
    | '/extension'
    | '/resellers-og'
    | '/api/public/download-extension'
  id:
    | '__root__'
    | '/'
    | '/admin-og'
    | '/extension'
    | '/resellers-og'
    | '/api/public/download-extension'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminOgRoute: typeof AdminOgRoute
  ExtensionRoute: typeof ExtensionRoute
  ResellersOgRoute: typeof ResellersOgRoute
  ApiPublicDownloadExtensionRoute: typeof ApiPublicDownloadExtensionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resellers-og': {
      id: '/resellers-og'
      path: '/resellers-og'
      fullPath: '/resellers-og'
      preLoaderRoute: typeof ResellersOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-og': {
      id: '/admin-og'
      path: '/admin-og'
      fullPath: '/admin-og'
      preLoaderRoute: typeof AdminOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-extension': {
      id: '/api/public/download-extension'
      path: '/api/public/download-extension'
      fullPath: '/api/public/download-extension'
      preLoaderRoute: typeof ApiPublicDownloadExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminOgRoute: AdminOgRoute,
  ExtensionRoute: ExtensionRoute,
  ResellersOgRoute: ResellersOgRoute,
  ApiPublicDownloadExtensionRoute: ApiPublicDownloadExtensionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
